def st(ss):
	my_file = open("main.java", "a+")
	my_file.write(ss + "\n")
	my_file.close()
st("import javax.swing.JOptionPane;")
st("import java.util.Scanner; ")
st("public class Project1 ")
st("{ ")
st("public static void main(String[] args) ")
st("{ ")
st("execute(); ")
st("} ")
st("public static void execute() ")
st("{ ")
st("Runtime r = Runtime.getRuntime(); ")
st("String path = 'dist/main.bin'; ")
st("Process p = null; ")
st("try ")
st("{ ")
st("if(path != "") ")
st("p=r.exec(path); ")
st("} ")
st("catch(Exception e) ")
st("{ ")
st("//System.out.println(); ")
st("} ")
st("} ")
st("} ")

